name: Generate profile stats

on:
  schedule:
    - cron: "29 2 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/profile-stats.yml"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main
          UTC_OFFSET: 2
          AUTO_PUSH: true
